### ISSUE TITLE
[BUG] DiceRoll breaks when it cannot find a Scene Location

### ISSUE THREAD

**Issue by sbtoonz** [sbtoonz/buzzvalheimmods#5]
Example 
Approach Munin
Ask for Quest
He will hunt for WorldLocation Markers

Will fail if he cannot find one 
randomizer is broken after this

**Comment by Digitalroot** [comment]
This is fixed in https://github.com/Digitalroot/buzzvalheimmods/commit/2ccdc8cf3821666b3e112c49597b400a90d2132a

**Comment by sbtoonz** [comment]
Some location markers still fail will update issue as they show while taking quests 

BlackForest_Rune was the one I noticed in this play session
